include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml

cache:
  - key:
      files:
        - package-lock.json
    paths:
      - .npm/
  - key:
      files:
        - composer.lock
    paths:
      - vendor/

lintphp:
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/php:7.4
  stage: test
  tags:
    - idmunisimple
  before_script:
    - apt-get update -yqq
    - apt-get install git unzip -yqq
    - php -r "copy('https://composer.github.io/installer.sig', 'installer.sig');"
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php -r "if (hash_file('SHA384', 'composer-setup.php') === file_get_contents('installer.sig')) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php'); unlink('installer.sig');"
    - php composer.phar install
  script:
    - vendor/bin/ecs check

.npm:
  before_script:
    - npm ci --cache .npm --prefer-offline

prettier:
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/node:14-buster
  stage: test
  tags:
    - idmunisimple
  extends:
    - .npm
  script:
    - npx prettier --check .

publish:
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/node:14-buster
  stage: deploy
  tags:
    - idmunisimple
  extends:
    - .npm
  script:
    - npx semantic-release
  rules:
    - if: $CI_DEFAULT_BRANCH == $CI_COMMIT_REF_NAME
